##Spam/Ham email classification using Bags of words technique with Naive bayes classifier

In [23]:
#importing libraries
import pandas as pd
import numpy as np
import nltk

In [24]:
#loading data
df=pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [25]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [27]:
# def get_spam_num(x):
#   if x=='spam':
#     return 1
#   else:
#     return 0

In [28]:
# df['spam']=df['Category'].apply(get_spam_num)

In [29]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [30]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [31]:
df.shape

(5572, 3)

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,train_size=0.82)

In [35]:
print('Shape of x_train ',x_train.shape)
print('Shape of y_train ',y_train.shape)
print('Shape of x_test ',x_test.shape)
print('Shape of y_test ',y_test.shape)

Shape of x_train  (4569,)
Shape of y_train  (4569,)
Shape of x_test  (1003,)
Shape of y_test  (1003,)


In [36]:
type(x_train)

pandas.core.series.Series

In [39]:
x_train[:4]

4694    Tessy..pls do me a favor. Pls convey my birthd...
1621    Fuck babe, I miss you sooooo much !! I wish yo...
1718    WOW! The Boys R Back. TAKE THAT 2007 UK Tour. ...
813     Congratulations ur awarded either £500 of CD g...
Name: Message, dtype: object

In [41]:
x_train[:4][4694]

'Tessy..pls do me a favor. Pls convey my birthday wishes to Nimya..pls dnt forget it. Today is her birthday Shijas'

In [38]:
y_train[:4]

4694    0
1621    0
1718    1
813     1
Name: spam, dtype: int64

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()
x_train_cv=vec.fit_transform(x_train.values) #creating numpy array
x_train_cv

<4569x7862 sparse matrix of type '<class 'numpy.int64'>'
	with 61249 stored elements in Compressed Sparse Row format>

In [45]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
x_train_cv.shape

(4569, 7862)

In [48]:
vec.get_feature_names_out()[10:30]

array(['0207', '02072069400', '02073162414', '02085076972', '021', '03',
       '04', '0430', '05', '050703', '0578', '06', '07', '07046744435',
       '07090298926', '07099833605', '07123456789', '0721072',
       '07732584351', '07742676969'], dtype=object)

In [50]:
vec.get_feature_names_out()[1000:1050]

array(['anot', 'another', 'ans', 'ansr', 'answer', 'answered',
       'answering', 'answers', 'answr', 'antha', 'anthony', 'anti',
       'antibiotic', 'any', 'anybody', 'anyhow', 'anymore', 'anyone',
       'anyones', 'anyplaces', 'anythin', 'anything', 'anythingtomorrow',
       'anytime', 'anyway', 'anyways', 'anywhere', 'aom', 'apart',
       'apartment', 'apes', 'apeshit', 'aphex', 'apnt', 'apo',
       'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applausestore',
       'applebees', 'apples', 'application', 'apply', 'applyed'],
      dtype=object)

In [51]:
vec.get_feature_names_out().shape

(7862,)

In [53]:
dir(vec) #will list all the methods of any library,module

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [54]:
vec.vocabulary_ #tells the position of position of words in vocabulary

{'tessy': 6894,
 'pls': 5344,
 'do': 2393,
 'me': 4482,
 'favor': 2828,
 'convey': 2018,
 'my': 4751,
 'birthday': 1385,
 'wishes': 7650,
 'to': 7053,
 'nimya': 4870,
 'dnt': 2392,
 'forget': 2982,
 'it': 3812,
 'today': 7059,
 'is': 3800,
 'her': 3455,
 'shijas': 6195,
 'fuck': 3068,
 'babe': 1210,
 'miss': 4589,
 'you': 7819,
 'sooooo': 6441,
 'much': 4718,
 'wish': 7648,
 'were': 7570,
 'here': 3456,
 'sleep': 6327,
 'with': 7656,
 'bed': 1306,
 'so': 6397,
 'lonely': 4256,
 'go': 3202,
 'now': 4925,
 'dream': 2468,
 'of': 4976,
 'love': 4292,
 'wow': 7725,
 'the': 6928,
 'boys': 1491,
 'back': 1218,
 'take': 6808,
 'that': 6924,
 '2007': 360,
 'uk': 7239,
 'tour': 7121,
 'win': 7630,
 'vip': 7413,
 'tickets': 7008,
 'pre': 5463,
 'book': 1447,
 'club': 1878,
 'txt': 7217,
 '81303': 665,
 'trackmarque': 7128,
 'ltd': 4317,
 'info': 3724,
 'vipclub4u': 7414,
 'congratulations': 1987,
 'ur': 7314,
 'awarded': 1191,
 'either': 2583,
 '500': 551,
 'cd': 1721,
 'gift': 3174,
 'vouchers':

In [55]:
vec.get_feature_names_out()[4104]

'law'

In [56]:
x_train_np=x_train_cv.toarray() #converting to numpy array
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

To see where are non zero values

In [58]:
np.where(x_train_np[0]!=0)

(array([1385, 2018, 2392, 2393, 2828, 2982, 3455, 3800, 3812, 4482, 4751,
        4870, 5344, 6195, 6894, 7053, 7059, 7650]),)

In [71]:
x_train[:4][1718]

'WOW! The Boys R Back. TAKE THAT 2007 UK Tour. Win VIP Tickets & pre-book with VIP Club. Txt CLUB to 81303. Trackmarque Ltd info@vipclub4u.'

#Model Training

In [72]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

#Testing & Evaluation

In [73]:
x_test_cv=vec.transform(x_test)

In [74]:
from sklearn.metrics import classification_report ##whenever you have imbalance dataset use classification_report instad of only accuracy
y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       873
           1       0.98      0.91      0.94       130

    accuracy                           0.99      1003
   macro avg       0.98      0.95      0.97      1003
weighted avg       0.99      0.99      0.99      1003



In [76]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9860418743768694


In [88]:
emails=[
    'Hey moahn,lets meet today yaar! ',
    'Upto @0% discount on your first shopping through credit card transactions',
    'Hey raghav ,Congratulations for getting placed in KPMG',
]

email_vec=vec.transform(emails)
model.predict(email_vec)

array([0, 1, 0])

#Alternative way using sklearn pipellining

In [92]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
 ('vectorizer',CountVectorizer()),
              ('nb',MultinomialNB())
 ])

In [93]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [95]:
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       873
           1       0.98      0.91      0.94       130

    accuracy                           0.99      1003
   macro avg       0.98      0.95      0.97      1003
weighted avg       0.99      0.99      0.99      1003



##                                                                Thank you!